# Generated by Django 3.2 on 2023-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('AUTH', 'Аутентифицированный пользователь'), ('Mod', 'Модератор'), ('Admin', 'Администратор'), ('SU', 'Суперюзер Django')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
