# Generated by Django 3.2 on 2023-06-22 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230621_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='До 1900огогода никто ничего не придумал'), django.core.validators.MaxValueValidator(2023, message='Не надодобавлять произведения из будущего')], verbose_name='год выхода'),
        ),
    ]
