# Generated by Django 3.2 on 2023-06-20 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230620_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900, message='До 1900ого года никто ничего не придумал'), django.core.validators.MaxValueValidator(2023, message='Не надо добавлять произведения из будущего')], verbose_name='год выхода'),
        ),
    ]
