# Generated by Django 3.2 on 2023-06-20 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1900, message='До 1900ого года никто ничего не придумал'), django.core.validators.MaxValueValidator(2023, message='Не надо добавлять произведения из будущего')], verbose_name='год выхода'),
            preserve_default=False,
        ),
    ]
