# Generated by Django 3.2 on 2023-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_title_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
